BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"
BBFILE_COLLECTIONS += "ultima-beagleplay"
BBFILE_PATTERN_ultima-beagleplay = "^${LAYERDIR}/"
BBFILE_PRIORITY_ultima-beagleplay = "10"
LAYERSERIES_COMPAT_ultima-beagleplay = "scarthgap"
LAYERDEPENDS_ultima-beagleplay = "core qt5-layer"
