BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bbappend"
BBFILE_COLLECTIONS += "falcon-beagleplay"
BBFILE_PATTERN_falcon-beagleplay = "^${LAYERDIR}/"
BBFILE_PRIORITY_falcon-beagleplay = "10"
LAYERSERIES_COMPAT_falcon-beagleplay = "scarthgap"
